### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Marius1311** [michalk8/scachepy#1]
In the requirements file, consider changing scanpy==1.4.3 to scanpy>= 1.4.3
Otherwise every user will always be downgraded to exactly that version when installing.

This also holds true for the other dependencies. I changed that manually and installed with anndata 0.6.22, however, that gives an error when I try to cache the neighbors function:

```python

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-b4278968b61d> in <module>
      1 # compute neighboors - PCA representation does already exist!
----> 2 c.pp.neighbors(adata)

~/Projects/scachepy/scachepy/utils.py in __call__(self, *args, **kwargs)
     13 
     14     def __call__(self, *args, **kwargs):
---> 15         return self._fn(*args, **kwargs)
     16 
     17     def __repr__(self):

~/Projects/scachepy/scachepy/scachepy.py in wrapper(*args, **kwargs)
    294 
    295             if len(args) > 0:
--> 296                 adata = args[0] if isinstance(args[0], (anndata.AnnData, anndata.base.Raw)) else kwargs.get('adata')
    297             else:
    298                 adata = kwargs.get('adata')

AttributeError: module 'anndata' has no attribute 'base'
```
Could you make it work with the current version of AnnData?

**Comment by michalk8** [comment]
I've update the requirements.txt, should be working with anndata version >= 0.6.22.

**Comment by Marius1311** [comment]
Checked it just now, works! Awesome!
